config/routes.rb
Rails.application.routes.draw do

  resources :sessions, only: [:new, :create]
  resources :products, only: [:new, :create, :index, :show]

  root to: 'sessions#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def ensure_configuration_is_set
    if session[:presta_shop_url].nil? || session[:presta_shop_api_key].nil?
      redirect_to new_session_path
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :ensure_configuration_is_set
  
  def new
    @product = ProductForm.new
  end

  def create
    @product = ProductForm.new(
      product_params.merge(
        url: session[:presta_shop_url],
        api_key: session[:presta_shop_api_key]
      )
    )

    if @product.save
      redirect_to products_path, notice: "Product #{@product.name} created successfully"
    else
      render :new
    end
  end

  def index
    @products = PrestashopProductsFinder.call(
      url: session[:presta_shop_url],
      api_key: session[:presta_shop_api_key]
    )
  end

  def show
    @product = PrestashopProductsFinder.call(
      url: session[:presta_shop_url],
      api_key: session[:presta_shop_api_key],
      product_id: params[:id]
    )
  end

  private

  def product_params
    params.require(:product_form).permit(:name, :reference, :price)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @session = SessionForm.new(
      presta_shop_url: session[:presta_shop_url],
      presta_shop_api_key: session[:presta_shop_api_key]
    )
  end

  def create
    @session = SessionForm.new(session_params)

    if @session.valid?
      assign_session_attrs
      redirect_to products_path
    else
      render :new
    end
  end

  private

  def session_params
    params.require(:session_form).permit(:presta_shop_url, :presta_shop_api_key)
  end

  def assign_session_attrs
    session[:presta_shop_url] = @session.presta_shop_url
    session[:presta_shop_api_key] = @session.presta_shop_api_key
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_flash_messages.html.erb
<% flash.each do |_, value| %>
  <p> <%= value %> </p>
<% end %>

app/views/application/_header.html.erb
<% if session[:presta_shop_url].present? && session[:presta_shop_api_key].present? %>
  <p> <%= "Current Prestaphop URL: #{session[:presta_shop_url]}" %> </p>
  <p> <%= "Current Prestaphop API KEY: #{session[:presta_shop_api_key]}" %> </p>
  <%= link_to 'Change credentials', new_session_path %>
<% end %>

</br>
</br>
</br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrestashopWrapper</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body align='center'>
    <%= render 'header' %>
    <%= render 'flash_messages' %>

    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<h1> Products list </h1>

<table align='center'>
  <thead>
    <th>ID</th>
    </th>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      </tr>
        <td> <%= "##{product[:id]}" %> </td>
        <td> <%= link_to "Detail", product_path(id: product[:id]) %> </td>
      </tr>
    <% end %>
  </tbody>
</table>

<h2> <%= link_to "New Product", new_product_path %> </h2>

app/views/products/new.html.erb
<h1> New product </h1>

<%= form_for @product, url: products_path do |f| %>
  <ul>
    <% @product.errors.full_messages.each do |error_message| %>
    <li> <%= error_message %> </li>
    <% end %>
  </ul>

  <%= f.label :name, 'Name' %>
  <%= f.text_field :name %>

  </br>
  </br>

  <%= f.label :reference, 'Reference' %>
  <%= f.text_field :reference %>

  </br>
  </br>

  <%= f.label :price, 'Price' %>
  <%= f.text_field :price %>

  </br>
  </br>

  <%= f.submit 'Save' %>
<% end %>

app/views/products/show.html.erb
<h1> Product detail </h1>

<p> <%= "##{@product[:id]}" %> </p>
<p> <%= "Mininal quantity: #{@product[:minimal_quantity]}" %> </p>
<p> <%= "Price: #{@product[:price]}" %> </p>
<p> <%= "Name: #{@product[:name]}" %> </p>

<%= link_to 'Back', :back %>